# Generated by Django 6.0.7 on 2026-07-25 19:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(help_text='sys_user.User ID. Immutable once created.', max_length=64, unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('default_title', models.CharField(blank=True, default='', max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['employee_code'],
            },
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('department_sha256', models.CharField(max_length=64)),
                ('user_sha256', models.CharField(max_length=64)),
                ('effective_date', models.DateField()),
                ('actor', models.CharField(max_length=64)),
                ('warnings', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'import_runs',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=32)),
                ('entity_type', models.CharField(max_length=32)),
                ('entity_id', models.CharField(blank=True, max_length=64, null=True)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'audit entries',
                'db_table': 'audit_entries',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='ix_audit_entity')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='cmn_department.ID. Immutable once created.', max_length=64, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_key', models.CharField(editable=False, max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='orgchart.department')),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
                ('sort_order', models.IntegerField()),
                ('effective_from', models.DateField(default=datetime.date(1, 1, 1))),
                ('effective_to', models.DateField()),
                ('source', models.CharField(choices=[('master', 'Excel import'), ('manual', 'Manual entry')], max_length=16)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='orgchart.department')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='orgchart.department')),
            ],
            options={
                'db_table': 'department_versions',
                'ordering': ['department_id', 'effective_to', 'id'],
                'indexes': [models.Index(fields=['department', 'effective_from', 'effective_to'], name='ix_deptver_as_of')],
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__gt', models.F('effective_from'))), name='ck_deptver_interval_non_empty')],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='The 本務. At most one open row per person.')),
                ('is_head', models.BooleanField(default=False, help_text='部門長. At most one open row per department.')),
                ('title_override', models.CharField(blank=True, help_text="Title held in this duty. Blank uses the employee's own title.", max_length=128, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Exclusive. Blank means open-ended.', null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('master', 'Excel import'), ('manual', 'Manual entry')], max_length=16)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assignments', to='orgchart.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assignments', to='orgchart.employee')),
            ],
            options={
                'db_table': 'assignments',
                'ordering': ['employee_id', '-is_primary', 'department_id'],
                'indexes': [models.Index(fields=['effective_from', 'effective_to'], name='ix_assignment_as_of')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('employee', 'department'), name='uq_assignment_open_pair'), models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True), ('is_primary', True)), fields=('employee',), name='uq_assignment_open_primary'), models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True), ('is_head', True)), fields=('department',), name='uq_assignment_open_head'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='ck_assignment_interval_non_empty')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('default_title', models.CharField(blank=True, default='', max_length=128)),
                ('active', models.BooleanField()),
                ('effective_from', models.DateField(default=datetime.date(1, 1, 1))),
                ('effective_to', models.DateField()),
                ('source', models.CharField(choices=[('master', 'Excel import'), ('manual', 'Manual entry')], max_length=16)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='orgchart.employee')),
            ],
            options={
                'db_table': 'employee_versions',
                'ordering': ['employee_id', 'effective_to', 'id'],
                'indexes': [models.Index(fields=['employee', 'effective_from', 'effective_to'], name='ix_empver_as_of')],
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__gt', models.F('effective_from'))), name='ck_empver_interval_non_empty')],
            },
        ),
    ]
